server:
    port: 8888
logging:
    level:
        root: INFO
spring:
    datasource:
        url: jdbc:h2:mem:entitydb
        driverClassName: org.h2.Driver
        username: qwerty
        password: qwerty
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            path: /h2-console
            enabled: true